---
- name: Converge
  hosts: all
  roles:
    - role: dmitrii-ageev.logrotate
      logrotate__files:
        - name: application
          path:
            - /var/log/application/*.log
          options:
            - weekly
            - rotate 4
            - compress
          scripts:
            postrotate: systemctl reload application &>/dev/null
        - name: syslog
          state: absent
