---
- name: "Create the configuration file"
  template:
    src: logrotate.conf.j2
    dest: "{{ logrotate__conf_file }}"
    owner: "{{ logrotate__user }}"
    group: "{{ logrotate__group }}"
    mode: "{{ logrotate__file_mode }}"
  when: logrotate__conf_file is defined

- name: Delete unwanted logrotate files
  file:
    path: "{{ logrotate__include_dir }}/{{ item.name }}"
    state: absent
  when: item.state|default() == 'absent'
  loop: "{{ logrotate__files | default([]) | flatten(levels=1) }}"

- name: Update individual logrotate configuration files
  template:
    src: logrotate.j2
    dest: "{{ logrotate__include_dir }}/{{ item.name }}"
    owner: "{{ logrotate__user }}"
    group: "{{ logrotate__group }}"
    mode: "{{ logrotate__file_mode }}"
  when: item.state|default() != 'absent'
  loop: "{{ logrotate__files | default([]) | flatten(levels=1) }}"
...
