---
- name: "Delete the configuration file"
  file:
    path: "{{ logrotate__conf_file }}"
    state: absent
  when: logrotate__conf_file is defined

- name: "Delete logrotate files"
  file:
    path: "{{ logrotate__include_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ logrotate__files | default([]) | flatten(levels=1) }}"
...
