---
- name: Add required repositories for Debian-based systems
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ logrotate__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] | default([]) }}"
  when: ansible_os_family == "Debian"

- name: Add required repositories for RedHat-based systems
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ logrotate__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] | default([]) }}"
  when: ansible_os_family == "RedHat"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ logrotate__packages[ansible_distribution][ansible_distribution_major_version|int]['required_packages'] | default([]) }}"
  notify: Restart cron service

- name: Install main packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ logrotate__packages[ansible_distribution][ansible_distribution_major_version|int]['packages'] | default([]) }}"
  notify: Restart cron service

- name: Create the application folder set
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ logrotate__user }}"
    group: "{{ logrotate__group }}"
    mode: "{{ logrotate__dir_mode }}"
  with_items: "{{ logrotate__directories | default([]) }}"

- name: Set logrotate__installed flag
  set_fact:
    logrotate__skip_installation: true
...
