---
- name: Uninstall {{ logrotate__service }}
  package:
    name: "{{ logrotate__main_packages }}"
    state: absent

- name: Delete the application folder set
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ logrotate__directories | default([]) | flatten(levels=1) }}"
...
